import Head from 'next/head'
import React from 'react'

import Header from '@/components/Header/Header'

type Props = {
  children: React.ReactNode
}

export default function Layout(props: Props) {
  return (
    <div className="bg-gray-100 min-h-screen flex flex-col w-screen items-center">
      <Head>
        <title>Бесіда</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="py-10 max-w-2xl w-full flex flex-col space-y-5">
        {props.children}
      </div>
    </div>
  )
}
